//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Space : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single Thruster
        {
            get
            {
                return SteamVR_Actions.space_Thruster;
            }
        }
        
        public virtual SteamVR_Action_Boolean Restart
        {
            get
            {
                return SteamVR_Actions.space_Restart;
            }
        }
        
        public virtual SteamVR_Action_Single Rewind
        {
            get
            {
                return SteamVR_Actions.space_Rewind;
            }
        }
        
        public virtual SteamVR_Action_Boolean TracePath
        {
            get
            {
                return SteamVR_Actions.space_TracePath;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThrustDirection
        {
            get
            {
                return SteamVR_Actions.space_ThrustDirection;
            }
        }
    }
}
